import axios from 'axios';
import Head from 'next/head'
import Features from '../components/Features'
import PizzaList from '../components/PizzaList'
import Add from '../components/Add'
import AddButton from '../components/Addbutton'
import { useState } from 'react';
import DelieveryProcess from '../components/DelieveryProcess';
import Map from '../components/Map';

export default function Home({pizzalist, admin}) {
  // const [close, setClose] = useState(true);

  return (
    <>
      <Head>
        <title>Pizza Ordering App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Features/>
     <PizzaList pizzalist={pizzalist} />
     {/* {!close && <Add setClose={setClose} />} */}
     <DelieveryProcess/>
     <Map/>

    </>
  );
}

// fetching pizzalist from database
export const getServerSideProps = async (ctx)=>{

  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

    const res = await axios.get("http://localhost:3000/api/products");

    return{
      props:{
        pizzalist: res.data,
        admin,
      }
    }
}

